'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.defaultSpeedoMeterProps = void 0;
var theme_1 = require('../../theme');
exports.defaultSpeedoMeterProps = {
  radius: 100,
  min: 0,
  max: 100,
  step: 1,
  value: 0,
  title: '',
  unit: 'MB/S',
  markerLineSize: 50,
  sliderWidth: 18,
  sliderTrackColor: theme_1.Colors.grey,
  lineColor: theme_1.Colors.grey,
  lineSpace: 3,
  linearGradient: [
    { offset: '0%', color: theme_1.Colors.skyBlue },
    { offset: '100%', color: theme_1.Colors.darkBlue },
  ],
  onChange: function (_v) {},
  onComplete: function (_v) {},
  openingRadian: Math.PI / 3,
  disabled: false,
  isHideSlider: false,
  isHideTitle: false,
  isHideSubtitle: false,
  isHideValue: false,
  isHideTailText: false,
  isHideLines: false,
  isHideMarkerLine: false,
  isHideCenterContent: false,
  fixedMarker: false,
  markerCircleSize: 15,
  markerCircleColor: theme_1.Colors.grey,
  markerPositionY: 20,
  markerPositionX: 20,
  needleBackgroundColor: 'purple',
  needleColor: '#175BAD',
  needleBorderWidth: 1.5,
  needleHeight: 30,
  variant: 'default',
  markerValueInterval: 10,
  markerValueColor: theme_1.Colors.darkCharcoal,
  strokeLinecap: 'butt',
};
