"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.horizontalScale = exports.verticalScale = exports.moderateScale = exports.Metrics = exports.Colors = void 0;
var Colors_1 = require("./Colors");
exports.Colors = Colors_1.default;
var Metrics_1 = require("./Metrics");
Object.defineProperty(exports, "Metrics", { enumerable: true, get: function () { return Metrics_1.Metrics; } });
Object.defineProperty(exports, "moderateScale", { enumerable: true, get: function () { return Metrics_1.moderateScale; } });
Object.defineProperty(exports, "verticalScale", { enumerable: true, get: function () { return Metrics_1.verticalScale; } });
Object.defineProperty(exports, "horizontalScale", { enumerable: true, get: function () { return Metrics_1.horizontalScale; } });
